packages:
  branch_codenames:
    master: bionic-unstable
    production: bionic-stable

jobs:
  runit_common:
    builder: "make"
    base: "quay.io/madebymany/build-bases:bionic"
    build_depends:
      - runit
      - postfix
    packages:
      - type: debian
        name: runit-common
        depends:
          - runit
          - postfix
        repos:
          - mxm-public
        promote_through:
          - unstable
          - stable
        target: install
