#!/bin/bash
set -eo pipefail

usage() {
cat <<-EOF
Usage:       runit-finish -n [name of service] 
Description: send out information on the stopped process, will log to syslog and send a message to Slack if the if the process fails 
EOF
}

if [[ $# -eq 0 ]]
then
    usage
    exit 1
fi

while getopts ":n:u:g:c:" o; do
    case "${o}" in
        n)
            name=${OPTARG}
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

env_vars="/etc/environment"
if [ -f "/etc/environment" ]; then
  eval $(sed -e "s/^/export /" "$env_vars")
fi

if [[ "$1" -eq "1" ]]; then
  slackcat "@channel $name failed to run"
fi

echo "stopping $name" | logger -t "$name"
