#!/bin/bash

set -e

SERVICE=$1; shift
DIRECTORY="/var/log/service/${SERVICE}"

eval "$(sed -e "s/^/export /" /etc/environment)"

if [[ ! -d $DIRECTORY ]]
then
  mkdir -p "$DIRECTORY"
fi

if [[ ! -r ${DIRECTORY}/config ]]
then
  echo -e "U127.0.0.1\np${SERVICE}: " >"${DIRECTORY}/config"
fi

chown -R logger:logger "$DIRECTORY"
echo "Starting logger for ${SERVICE} service..."
cd "$DIRECTORY"
exec chpst -u logger svlogd "$DIRECTORY"
